#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# BCAI website — domain registration, DNS, Let's Encrypt (Caddy), .env, and deploy.
# Generated by the /wizard skill. Run from repo root: ./scripts/go-live-domain-ssl.sh
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=11
TOTAL_MINUTES=50

VPS_IP="${VPS_IP:-135.181.39.41}"
N8N_ENV_PATH="${N8N_ENV_PATH:-/opt/n8n/.env}"
HTML_FILES=(
  index.html workshops.html workshop.html workshop-1.html workshop-2.html workshop-3.html
  what-we-automate.html workshop-one-pager.html
)

banner "BCAI website — domain + SSL go-live"

# ── 1. Prerequisites ───────────────────────────────────────────────────────
stage "Prerequisites — VPS is running" 3
say "The site should already be live on the VPS IP before you add a domain."
step "Open the current site and confirm pages load."
open_url "http://${VPS_IP}/"
step "Confirm Docker is up on the VPS (ssh root@${VPS_IP} → docker compose ps in /opt/web_site)."
note "If this is a fresh VPS, follow README.md → First-time setup on VPS first."
pause "Site loads on the IP and docker compose is healthy?"

# ── 2. Register domain ─────────────────────────────────────────────────────
stage "Register your .ie domain" 10
say "Planned domain for this site: ai-development.ie (change below if different)."
note ".ie domains require registration through an accredited .ie registrar and proof of connection to Ireland."
open_url "https://www.weare.ie/en/register-a-domain-name/"
step "Register your domain (or confirm you already own it)."
step "Note your registrar login — you'll need it for DNS in the next stage."
ask DOMAIN "Domain name (e.g. ai-development.ie):"
DOMAIN="${DOMAIN:-ai-development.ie}"
DOMAIN="${DOMAIN#https://}"
DOMAIN="${DOMAIN#http://}"
DOMAIN="${DOMAIN%/}"
ask ACME_EMAIL "Email for Let's Encrypt expiry notices (e.g. karlnolancompany@gmail.com):"
ACME_EMAIL="${ACME_EMAIL:-karlnolancompany@gmail.com}"
pause "Domain registered or already in your account?"

# ── 3. DNS A record ────────────────────────────────────────────────────────
stage "DNS — point domain at the VPS" 5
say "Create DNS records at your registrar (exact UI varies by provider)."
step "Add an A record:  @  →  ${VPS_IP}   (TTL 300–3600 is fine)."
step "Optional but recommended:  www  →  ${VPS_IP}   (or CNAME www → ${DOMAIN})."
note "Do not enable registrar 'parking' or a proxy that hides the VPS IP until Caddy has issued a cert."
open_url "https://dnschecker.org/#A/${DOMAIN}"
pause "DNS records saved at the registrar?"

# ── 4. Wait for propagation ───────────────────────────────────────────────
stage "DNS — wait for propagation" 5
say "Let's Encrypt needs the A record visible from the public internet."
step "On dnschecker.org, confirm most locations show ${VPS_IP} for ${DOMAIN}."
step "Locally:  dig +short ${DOMAIN}   (should print ${VPS_IP})."
if ! dig +short "$DOMAIN" 2>/dev/null | grep -qFx "$VPS_IP"; then
  warn "dig did not return ${VPS_IP} yet — you can continue configuring, but do not deploy Caddy until DNS is correct."
else
  note "dig looks good from this machine."
fi
pause "DNS resolves to ${VPS_IP} (or you're willing to wait and re-check before deploy)?"

# ── 5. Site .env URLs ──────────────────────────────────────────────────────
stage "Configure site .env URLs" 3
say "Production URLs for the static site container (rendered into js/site-config.js at start)."
BASE_URL="https://${DOMAIN}"
write_env CANONICAL_URL "${BASE_URL}/"
write_env BOOKING_SUCCESS_URL "${BASE_URL}/index.html?call-booked=1"
write_env ASSESSMENT_URL "${BASE_URL}/assessment"
write_env CHAT_WEBHOOK_URL "${BASE_URL}/webhook/bcai-website-chat/chat"
write_env CHAT_WARM_CACHE_URL "${BASE_URL}/webhook/bcai-warm-knowledge"
write_env BOOKING_URL "${BASE_URL}/webhook/booking"
note "Committed .env is gitignored — you'll copy this file to the VPS in the deploy stage."

# ── 6. Caddyfile — Let's Encrypt ───────────────────────────────────────────
stage "Caddy — switch from IP cert to domain TLS" 5
say "Caddy will obtain a real Let's Encrypt certificate once DNS points here and this file is deployed."
CADDYFILE="docker/Caddyfile"
if [[ -f "$CADDYFILE" && ! -f "${CADDYFILE}.bak" ]]; then
  cp "$CADDYFILE" "${CADDYFILE}.bak"
  note "Backed up ${CADDYFILE} → ${CADDYFILE}.bak"
fi
if confirm "Write ${CADDYFILE} for ${DOMAIN} + www (replaces self-signed :443 block)?"; then
  cat > "$CADDYFILE" <<CADDYEOF
(common_n8n) {
	handle /webhook/* {
		reverse_proxy n8n:5678
	}
	handle /rest/oauth2-credential/* {
		reverse_proxy n8n:5678
	}
}

(ai_ivr) {
	handle /webhooks/* {
		reverse_proxy ai_ivr:8000
	}
	handle /api/* {
		reverse_proxy ai_ivr:8000
	}
	handle /admin/* {
		reverse_proxy ai_ivr:8000
	}
	handle /static/* {
		reverse_proxy ai_ivr:8000
	}
	handle /dev/* {
		reverse_proxy ai_ivr:8000
	}
	handle /health {
		reverse_proxy ai_ivr:8000
	}
	handle /assessment {
		rewrite * /
		reverse_proxy ai_ivr:8000
	}
}

# HTTP: keep webhook POST endpoints reachable without TLS redirect (Retell/n8n).
:80 {
	import common_n8n
	handle /webhooks/* {
		reverse_proxy ai_ivr:8000
	}
	handle {
		redir https://{host}{uri} permanent
	}
}

# HTTPS: Let's Encrypt via Caddy (automatic once DNS is live).
${DOMAIN}, www.${DOMAIN} {
	tls ${ACME_EMAIL}
	import common_n8n
	import ai_ivr
	handle {
		reverse_proxy site:8080
	}
}
CADDYEOF
  note "Wrote ${CADDYFILE} — IP-only self-signed TLS (docker/ssl) is no longer used for HTTPS."
else
  warn "Skipped Caddyfile write — edit ${CADDYFILE} manually before deploy."
fi

# ── 7. HTML canonical + Open Graph tags ────────────────────────────────────
stage "HTML — canonical and og:url tags" 5
say "Replace hardcoded http://${VPS_IP} URLs with https://${DOMAIN} in page HTML."
OLD_PREFIX="http://${VPS_IP}"
NEW_PREFIX="https://${DOMAIN}"
if confirm "Update ${#HTML_FILES[@]} HTML files (${OLD_PREFIX} → ${NEW_PREFIX})?"; then
  for f in "${HTML_FILES[@]}"; do
    if [[ -f "$f" ]]; then
      if perl -pi -e "s|\Q${OLD_PREFIX}\E|${NEW_PREFIX}|g" "$f" 2>/dev/null; then
        note "  updated $f"
      else
        warn "  could not update $f"
      fi
    fi
  done
  note "Also check js/site-config.js if you run the site without Docker entrypoint locally."
else
  warn "Skipped HTML updates — search repo for ${VPS_IP} and update before go-live."
fi

# ── 8. n8n production env ──────────────────────────────────────────────────
stage "n8n — production webhook base URL" 5
say "n8n on the VPS (/opt/n8n) must know the public HTTPS webhook URL."
note "These lines belong in ${N8N_ENV_PATH} on the server (not the web_site .env)."
cat <<N8NENV

# Add or update in ${N8N_ENV_PATH}:
N8N_PUBLIC_HOST=${DOMAIN}
N8N_PROTOCOL=https
WEBHOOK_URL=${BASE_URL}/
N8N_EDITOR_BASE_URL=https://${DOMAIN}:5678/

N8NENV
step "SSH to the VPS and edit ${N8N_ENV_PATH}, or paste the block above."
step "Then:  cd /opt/n8n && docker compose up -d"
pause "n8n .env updated on the VPS (or you'll do it before smoke test)?"

# ── 9. n8n workflows — CORS + redirects ────────────────────────────────────
stage "n8n — workflow URLs (manual in editor)" 8
say "Workflow JSON in git still references the IP — update live workflows in n8n after deploy."
open_url "http://${VPS_IP}:5678"
step "BCAI Website Chatbot → Chat Trigger → Allowed Origins: add https://${DOMAIN}"
step "Discovery Call Booking → Redirect to Site node: success URL → ${BASE_URL}/index.html?call-booked=1"
step "Discovery Call Booking → OpenRouter HTTP-Referer headers → ${BASE_URL}/booking"
step "Re-activate workflows after saving."
note "Later: export workflows back to n8n/*.workflow.json and commit."
pause "Workflow URLs updated in n8n (or scheduled right after deploy)?"

# ── 10. Deploy to VPS ──────────────────────────────────────────────────────
stage "Deploy — push config to the VPS" 5
say "Commit and push repo changes, then restart containers on the server."
step "Locally: git add docker/Caddyfile .env *.html && git commit && git push"
step "On VPS:"
cat <<DEPLOY

  ssh root@${VPS_IP}
  cd /opt/web_site
  git pull
  # copy .env if not synced another way:
  # scp .env root@${VPS_IP}:/opt/web_site/.env
  docker compose up -d --build
  docker compose logs -f caddy   # watch for ACME / certificate success

DEPLOY
if confirm "Ready to deploy now (you will run the commands above)?"; then
  note "Deploy when DNS is correct — Caddy retries ACME if it fails the first time."
else
  note "Re-run this wizard anytime; .env values are idempotent."
fi
pause "Deploy complete (or you'll deploy when DNS is ready)?"

# ── 11. Verify SSL + smoke test ────────────────────────────────────────────
stage "Verify HTTPS and smoke test" 5
open_url "https://${DOMAIN}/"
step "Browser shows a valid padlock (Let's Encrypt, not self-signed)."
step "Home, workshops, chat widget, and discovery booking still work."
step "Optional:  curl -sI https://${DOMAIN}/ | head   (expect HTTP/2 200)."
step "Optional:  echo | openssl s_client -connect ${DOMAIN}:443 -servername ${DOMAIN} 2>/dev/null | openssl x509 -noout -issuer -dates"
open_url "https://www.ssllabs.com/ssltest/analyze.html?d=${DOMAIN}"
pause "HTTPS verified and smoke tests passed?"

finish
